# Generated by Django 6.1.1 on 2026-10-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='captchachallenge',
            name='comments_ca_expires_5253b9_idx',
        ),
        migrations.DeleteModel(
            name='CaptchaChallenge',
        ),
    ]
