# Generated by Django 6.1.1 on 2026-10-06 22:10

import comments.models.attachment
import comments.models.markup
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_captchachallenge_comments_ca_expires_5253b9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=comments.models.attachment.attachment_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png', 'txt'])])),
                ('original_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('kind', models.CharField(blank=True, choices=[('image', 'Image'), ('text', 'Text file')], editable=False, max_length=5)),
                ('size', models.PositiveIntegerField(default=0, editable=False)),
                ('width', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comment attachment',
                'verbose_name_plural': 'Comment attachments',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='commentauthor',
            options={'verbose_name': 'Comment author', 'verbose_name_plural': 'Comment authors'},
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='comments.commentauthor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='homepage',
            field=models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=10000, validators=[comments.models.markup.validate_comment_text]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(db_index=True, max_length=80, validators=[django.core.validators.RegexValidator('\\A[A-Za-z0-9]+\\Z', 'Use Latin letters and digits only.')]),
        ),
        migrations.AlterField(
            model_name='commentauthor',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='commentauthor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='commentauthor',
            name='homepage',
            field=models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='commentauthor',
            name='username',
            field=models.CharField(max_length=80, validators=[django.core.validators.RegexValidator('\\A[A-Za-z0-9]+\\Z', 'Use Latin letters and digits only.')]),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='comments_no_self_reply'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('quoted_comment', models.F('id')), _negated=True), name='comments_no_self_quote'),
        ),
        migrations.AddConstraint(
            model_name='commentauthor',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='comments_author_identity'),
        ),
        migrations.AddField(
            model_name='commentattachment',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='comments.comment'),
        ),
    ]
