[project]
name = "dzen-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "docker>=7.2.0",
    "dotenv>=0.9.9",
    "psycopg>=3.3.6",
    "websockets>=17.2",
]

[project.scripts]
dzen-code = "dzen_code:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
